const projects = [
  {
    id: 'project1',
    title: 'Dicomed',
    img: '/project1/project1.png',
    link: '/projects/project1',
    date: '2025',
    company: 'Rookminiinfosolution',
    liveLink: 'https://dicomed.io/',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mov',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project1/3.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/4.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project1/5.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project1/7.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project1/9.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/10.png',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Dicomed is an AI-powered clinical workflow platform covering telemedicine, radiology analysis, and automated SOAP note and prescription generation.',
      'I built it end-to-end with a Next.js and TypeScript frontend and an Express/NestJS backend, integrating Azure AI models and custom AI models for clinical documentation and imaging analysis.',
      'The platform includes secure clinical data storage, role-based access control, and audit logging, deployed across Azure and Hostinger infrastructure.',
    ],
  },
  {
    id: 'project2',
    title: 'Truzh',
    img: '/project2/project2.png',
    link: '/projects/project2',
    date: '2025',
    company: 'Rookminiinfosolution',
    liveLink: 'https://truzh.com/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mov',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project2/3.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Truzh is a social commerce marketplace combining product listings, community clans, and real-time messaging in one platform.',
      'I built it end-to-end with a Next.js and TypeScript frontend and an Express/NestJS backend, covering listings, favorites, requests, and in-app messaging.',
      'The platform is deployed across Azure and Hostinger infrastructure, built for scalable multi-role marketplace interactions.',
    ],
  },
  {
    id: 'project3',
    title: 'ExpertOnHire',
    img: '/project3/project3.png',
    link: '/projects/project3',
    date: '2025',
    liveLink: 'https://expertonhire.com/',
    company: 'Rookminiinfosolution',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mov',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/2.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project3/3.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/4.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project3/5.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/6.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project3/7.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/8.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project3/9.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/10.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project3/11.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'ExpertOnHire is an HR and freelance marketplace platform in the style of Upwork, connecting businesses with multi-role professionals.',
      'I built it end-to-end with a Next.js and TypeScript frontend and an Express/NestJS backend, handling authentication, real-time interactions, and structured hiring workflows.',
      'The platform is containerized with Docker and deployed across Azure and Hostinger, with Kafka-based microservices enabling asynchronous, event-driven processing.',
    ],
  },
  {
    id: 'project4',
    title: 'DocPad',
    img: '/project4/project4.png',
    link: '/projects/project4',
    date: '2025',
    company: 'Rookminiinfosolution',
    liveLink: 'https://docpad.io/',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/4.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/5.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/7.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/8.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/11.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/12.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/13.png',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'DocPad is an email marketing platform covering campaign creation, sending, and automated reply management in one workflow.',
      'I built the platform end-to-end with a Next.js and TypeScript frontend and an Express/NestJS backend, handling campaign scheduling, deliverability, and inbox reply tracking.',
      'The platform is deployed across Hostinger and Azure infrastructure, built for reliable, scalable outbound campaign delivery.',
    ],
  },
  {
    id: 'project5',
    title: 'DNS Maritime',
    img: '/project5/project5.png',
    link: '/projects/project5',
    date: '2025',
    company: 'Rookminiinfosolution',
    liveLink: 'https://dnsmaritime.com/',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/3.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/4.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/7.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/9.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/10.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/11.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'DNS Maritime is a maritime operations management platform for supplying goods to vessels, with full delivery tracking and record-keeping.',
      'I built it end-to-end with a Next.js and TypeScript frontend and an Express/NestJS backend, covering order records, delivery workflows, and vessel operations.',
      'The platform is deployed across Hostinger and Azure infrastructure, built for reliable operational record-keeping.',
    ],
  },
];
export default projects;
